name: Build, test and push images

env:
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres

on:
  push:
    branches:
      - main

jobs:
  backend_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql password: $POSTGRES_PASSWORD
      - name: Test backend
        working-directory: backend
        run: |
          rustup default nightly
          POSTGRES_PORT=5432 POSTGRES_HOST=127.0.0.1 cargo test -j 1

  build_backend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: backend_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push backend image
        working-directory: backend
        env:
          IMAGE_TAG: ghcr.io/t-x-t/txts-treasury/backend:${{ github.ref_name }}
        run: |
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

  build_frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push frontend image
        working-directory: frontend
        env:
          IMAGE_TAG: ghcr.io/t-x-t/txts-treasury/frontend:${{ github.ref_name }}
        run: |
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
